import {
  KiyoButton,
  KiyoButtonGroup,
  KiyoIcon,
  KiyoCollapse,
  KiyoCollapseItem,
  KiyoAlert,
  KiyoTooltip,
  KiyoPopconfirm,
  KiyoDropdown,
  KiyoDropdownItem,
  KiyoMessage,
  KiyoNotification,
  KiyoMessageBox,
  KiyoInput,
  KiyoSwitch,
  KiyoLoading,
} from "@kiyo-element/components";
import type { Plugin } from "vue";

export default [
  KiyoButton,
  KiyoButtonGroup,
  KiyoIcon,
  KiyoCollapse,
  KiyoCollapseItem,
  KiyoAlert,
  KiyoTooltip,
  KiyoPopconfirm,
  KiyoDropdown,
  KiyoDropdownItem,
  KiyoMessage,
  KiyoNotification,
  KiyoMessageBox,
  KiyoInput,
  KiyoSwitch,
  KiyoLoading,
] as Plugin[];
