# name: Deploy Docs

# on: #job触发条件
#   push:
#     branches: [master]

# permissions:
#   contents: read # 读取代码
#   pages: write # 写入 GitHub Pages
#   id-token: write # 用于身份验证

# jobs:
#   build:
#     runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统
#     steps:
#       # 1. 拉取代码
#       - uses: actions/checkout@v4

#       # 2. 安装 PNPM
#       - uses: pnpm/action-setup@v2
#         with:
#           version: 10.28.1

#       # 3. 安装 Node.js
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: "pnpm" # 启用 PNPM 缓存加速

#       # 4. 安装依赖
#       - run: pnpm install --frozen-lockfile

#       # 5. 构建核心库
#       - run: pnpm build

#       # 6. 构建文档
#       - run: pnpm --filter @kiyo-element/docs build

#       # 7. 配置 GitHub Pages
#       - uses: actions/configure-pages@v4

#       # 8. 上传构建产物
#       - uses: actions/upload-pages-artifact@v3
#         with:
#           path: packages/docs/.vitepress/dist # 上传文档构建结果

#   deploy:
#     environment:
#       name: github-pages # 部署到 GitHub Pages 环境
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build # 依赖 build 任务完成
#     steps:
#       # 部署到 GitHub Pages
#       - uses: actions/deploy-pages@v4
name: Test and deploy

on:
  push:
    branches:
      - master

jobs:
  # test:
  #   name: Run Lint and Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Setup Node
  #       uses: actions/setup-node@v3

  #     - name: Install pnpm
  #       run: npm install -g pnpm

  #     - name: Install dependencies
  #       run: pnpm install --frozen-lockfile

  #     - name: Run tests
  #       run: pnpm run test

  build:
    name: Build docs
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: build component
        run: pnpm run build

      - name: Build docs
        run: pnpm run docs:build

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./packages/docs/.vitepress/dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download docs
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .
